language: python
python:
    - "3.5"
    - "3.6"
    
addons:
    code_climate:
        repo_token: 8e082865964ccd108f3ebb080900055fdda5df4763d6b4f08b3872aa8ef6b0e4

script: ./test.sh
after_sucess:
  - CODECLIMATE_REPO_TOKEN=8e082865964ccd108f3ebb080900055fdda5df4763d6b4f08b3872aa8ef6b0e4 codeclimate-test-reporter --file markdown_outline/tests/.coverage
